#!/bin/bash
#SBATCH --job-name=idmapping
#SBATCH --ntasks=1
#SBATCH --mem=5gb
#SBATCH --time=12:00:00
#SBATCH --partition=standard
#SBATCH --account=shaneburgess

#THIS SCRIPT TAKES THE UNILNC IDS FROM GFFCOMPARE AND MAKES A TABULAR MAPPING FILE FOR ALL TISSUES TO CORRELATE NEW ID WITH ORIGINAL ID.

#################################################################################################################################################

tracking="/xdisk/shaneburgess/amcooksey/usda_ncrna_annotation/mRNA/drechsler_chicken/FEELnc/unified_lncrna_ids.tracking"

tissuearray=(isthmus magnum shellgland)

cd /xdisk/shaneburgess/amcooksey/usda_ncrna_annotation/mRNA/drechsler_chicken/FEELnc

for i in "${!tissuearray[@]}"
        do
        tissue=${tissuearray[$i]}
        rm $tissue/"$tissue"_lncRNA_mapping.txt
        touch $tissue/"$tissue"_lncRNA_mapping.txt $tissue/"$tissue"_temp.txt
        query=$(( 1 + $i ))
        column=$(( $i + 5 ))
        grep q"$query" unified_lncrna_ids.tracking | cut -f 1,2,$column > $tissue/"$tissue"_temp.txt
        sed -i 's/q[0-9]://g' $tissue/"$tissue"_temp.txt
        cat $tissue/"$tissue"_temp.txt | while read -r unilnc xloc id remainder
                do
                gene=$(echo $id | cut -f3 | cut -d '|' -f1)
                lnc=$(echo $id | cut -f3 | cut -d '|' -f2)
		if [[ "$gene" != "-" ]]
			then
			        echo -e "$unilnc\t$xloc\t$gene\t$lnc" >> $tissue/"$tissue"_lncRNA_mapping.txt
		fi        
	done
        rm $tissue/"$tissue"_temp.txt
done

